version: '2'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - 9090:9090/tcp
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana-container
    ports:
      - 3000:3000/tcp
    user: "104"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
volumes:
  grafana_data:
